services:
  db:
    image: postgres:15
    container_name: postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    # Wait for PostgreSQL container
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d mydb"]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    build: ./server
    container_name: backend
    env_file: .env
    volumes:
      - ./server:/app
      - ./server/resumes:/app/resumes
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
    environment:
      DB_HOSTNAME: db
      DB_NAME: mydb
      DB_USERNAME: user
      DB_PASSWORD: pass
      DB_PORT: 5432

  frontend:
    build: ./client
    container_name: frontend
    env_file: .env
    volumes:
      - ./client:/app
    ports:
      - "3000:3000"
    depends_on:
      - backend

volumes:
  pgdata:
