"""Add phone column

Revision ID: 185e949dba47
Revises: 
Create Date: 2025-09-13 19:52:04.901267

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '185e949dba47'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('leads', sa.Column('phone', sa.String(), nullable=True))
    op.alter_column('leads', 'firstName',
               existing_type=sa.VARCHAR(length=45),
               nullable=True)
    op.alter_column('leads', 'lastName',
               existing_type=sa.VARCHAR(length=45),
               nullable=True)
    op.alter_column('leads', 'email',
               existing_type=sa.VARCHAR(length=128),
               nullable=True)
    op.alter_column('leads', 'state',
               existing_type=sa.VARCHAR(length=45),
               nullable=True)
    op.create_index(op.f('ix_leads_email'), 'leads', ['email'], unique=True)
    op.create_index(op.f('ix_leads_id'), 'leads', ['id'], unique=False)
    op.alter_column('users', 'role',
               existing_type=sa.VARCHAR(length=45),
               nullable=True)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.alter_column('users', 'role',
               existing_type=sa.VARCHAR(length=45),
               nullable=False)
    op.drop_index(op.f('ix_leads_id'), table_name='leads')
    op.drop_index(op.f('ix_leads_email'), table_name='leads')
    op.alter_column('leads', 'state',
               existing_type=sa.VARCHAR(length=45),
               nullable=False)
    op.alter_column('leads', 'email',
               existing_type=sa.VARCHAR(length=128),
               nullable=False)
    op.alter_column('leads', 'lastName',
               existing_type=sa.VARCHAR(length=45),
               nullable=False)
    op.alter_column('leads', 'firstName',
               existing_type=sa.VARCHAR(length=45),
               nullable=False)
    op.drop_column('leads', 'phone')
    # ### end Alembic commands ###
